# Generated by Django 4.0.3 on 2022-04-02 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Expect',
            new_name='Order',
        ),
    ]
