# Generated by Django 4.0.1 on 2022-04-02 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Expect',
        ),
    ]
