# Generated by Django 4.0.1 on 2022-04-06 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_rename_expect_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='trailer',
            field=models.URLField(default='', max_length=500),
        ),
    ]
